-- MySQL Script generated by MySQL Workbench
-- Tue Jul 25 11:17:14 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuario` (
  `tip_id` INT NOT NULL AUTO_INCREMENT,
  `tip_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tip_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `usu_id` INT NOT NULL AUTO_INCREMENT,
  `usu_nombre` VARCHAR(45) NOT NULL,
  `usu_apellido` VARCHAR(45) NOT NULL,
  `usu_cedula` VARCHAR(10) NOT NULL,
  `usu_contraseña` VARCHAR(45) NULL,
  `tipo_usuario_tip_id` INT NOT NULL,
  `administrador_adm_id` INT NOT NULL,
  PRIMARY KEY (`usu_id`),
  INDEX `fk_usuarios_tipo_usuario1_idx` (`tipo_usuario_tip_id` ASC),
  CONSTRAINT `fk_usuarios_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_tip_id`)
    REFERENCES `mydb`.`tipo_usuario` (`tip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modalidad` (
  `mod_id` INT NOT NULL AUTO_INCREMENT,
  `mod_modalidad` VARCHAR(45) NULL,
  PRIMARY KEY (`mod_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`juegos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`juegos` (
  `jue_id` INT NOT NULL,
  `jue_nombre` VARCHAR(45) NULL,
  `jue_valor` FLOAT NULL,
  `jue_imagen` BINARY(50) NULL,
  `jue_minins` INT NULL,
  `jue_maxins` INT NULL,
  `modalidad_mod_id` INT NOT NULL,
  `administrador_adm_id` INT NOT NULL,
  PRIMARY KEY (`jue_id`),
  INDEX `fk_juegos_modalidad1_idx` (`modalidad_mod_id` ASC),
  CONSTRAINT `fk_juegos_modalidad1`
    FOREIGN KEY (`modalidad_mod_id`)
    REFERENCES `mydb`.`modalidad` (`mod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inscripciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inscripciones` (
  `ins_id` INT NOT NULL AUTO_INCREMENT,
  `ins_nombre` VARCHAR(45) NOT NULL,
  `ins_apellido` VARCHAR(45) NOT NULL,
  `jug_fechains` DATE NOT NULL,
  `usuarios_usu_id` INT NOT NULL,
  `juegos_jue_id` INT NOT NULL,
  PRIMARY KEY (`ins_id`),
  INDEX `fk_jugadores_usuarios1_idx` (`usuarios_usu_id` ASC),
  INDEX `fk_jugadores_juegos1_idx` (`juegos_jue_id` ASC),
  CONSTRAINT `fk_jugadores_usuarios1`
    FOREIGN KEY (`usuarios_usu_id`)
    REFERENCES `mydb`.`usuarios` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugadores_juegos1`
    FOREIGN KEY (`juegos_jue_id`)
    REFERENCES `mydb`.`juegos` (`jue_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`enfrentamientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`enfrentamientos` (
  `enf_id` INT NOT NULL,
  `enf_resultado` VARCHAR(45) NOT NULL,
  `jugadores_jug_id` INT NOT NULL,
  PRIMARY KEY (`enf_id`),
  INDEX `fk_enfrentamientos_jugadores1_idx` (`jugadores_jug_id` ASC),
  CONSTRAINT `fk_enfrentamientos_jugadores1`
    FOREIGN KEY (`jugadores_jug_id`)
    REFERENCES `mydb`.`inscripciones` (`ins_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
